=== eddie-energy/eddie/cim/src/main/schemas/agnostic/json/connection-status-message.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://eddie.energy/agnostic/connection-status-message",
  "type": "object",
  "properties": {
    "connectionId": {
      "description": "ID given by the eligible party to the permission request",
      "type": "string"
    },
    "permissionId": {
      "description": "Unique ID of the permission request",
      "$ref": "shared.json#/$defs/uuid"
    },
    "dataNeedId": {
      "description": "Data need related to the permission request",
      "$ref": "shared.json#/$defs/uuid"
    },
    "dataSourceInformation": {
      "$ref": "shared.json#/$defs/dataSourceInformation"
    },
    "timestamp": {
      "description": "Creation timestamp of this message",
      "type": "string",
      "format": "date-time"
    },
    "status": {
      "description": "The new status of the permission request",
      "type": "string",
      "enum": [
        "CREATED",
        "VALIDATED",
        "MALFORMED",
        "UNABLE_TO_SEND",
        "SENT_TO_PERMISSION_ADMINISTRATOR",
        "TIMED_OUT",
        "ACCEPTED",
        "REJECTED",
        "INVALID",
        "REVOKED",
        "TERMINATED",
        "FULFILLED",
        "UNFULFILLABLE",
        "REQUIRES_EXTERNAL_TERMINATION",
        "FAILED_TO_TERMINATE",
        "EXTERNALLY_TERMINATED"
      ]
    },
    "message": {
      "description": "Can contain a reason for the status change",
      "type": [
        "null",
        "string"
      ]
    },
    "additionalInformation": {
      "description": "Any additional information about the permission request, does not follow any schema.",
      "type": [
        "object",
        "null"
      ]
    }
  },
  "required": [
    "connectionId",
    "permissionId",
    "dataNeedId",
    "dataSourceInformation",
    "timestamp",
    "status",
    "message",
    "additionalInformation"
  ]
}

=== eddie-energy/eddie/cim/src/test/resources/agnostic/connectionStatusMessageList.json
[
  {
    "connectionId": "1",
    "permissionId": "5c945d84-8120-4f30-9c69-2dc1dbbb4a43",
    "dataNeedId": "9bd0668f-cc19-40a8-99db-dc2cb2802b17",
    "dataSourceInformation": {
      "countryCode": "DE",
      "meteredDataAdministratorId": "sim",
      "permissionAdministratorId": "sim",
      "regionConnectorId": "sim"
    },
    "timestamp": "2026-07-13T00:00:00.000000000Z",
    "status": "CREATED",
    "message": "",
    "additionalInformation": null
  },
  {
    "connectionId": "1",
    "permissionId": "5c945d84-8120-4f30-9c69-2dc1dbbb4a43",
    "dataNeedId": "9bd0668f-cc19-40a8-99db-dc2cb2802b17",
    "dataSourceInformation": {
      "countryCode": "DE",
      "meteredDataAdministratorId": "sim",
      "permissionAdministratorId": "sim",
      "regionConnectorId": "sim"
    },
    "timestamp": "2026-07-13T00:00:00.000000000Z",
    "status": "VALIDATED",
    "message": "",
    "additionalInformation": null
  }
]
